django-polls/polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    # ex: /polls/
    path("", views.index, name="index"),
    # ex: /polls/login/
    path("login/", views.login_view, name="login"),
    # ex: /polls/logout/
    path("logout/", views.register, name="register"),
    # ex: /polls/register/
    path("register/", views.logout_view, name="logout"),
    # ex: /polls/5/ 
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    # ex: /polls/5/results/
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    # ex: /polls/5/vote/
    path("<int:question_id>/vote/", views.vote, name="vote"),
    #ex: /polls/profile/
    path("profile/", views.profile, name="profile"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("polls/", include("polls.urls", namespace="polls")),
    path("polls/", include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
]

django-polls/polls/models.py
import datetime
from django.contrib import admin
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

# Create your models here.


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text
    
    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


class Account(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    last_poll_id = models.IntegerField(default=0)


class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
    vote_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'choice')

django-polls/polls/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.utils import timezone
from django.views import generic
from django.views.decorators.csrf import csrf_exempt
import traceback

from .models import Account, Choice, Question, Vote

# Create your views here.


TO_LOGIN = 'polls:login'

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("polls:index"))
        else:
            messages.error(request,'Username or password is not correct.')
            return redirect(TO_LOGIN)
    else:
        return render(request, "polls/login.html")


def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        email = request.POST['email']
        try:        
            user = User.objects.create_user(username=username, password=password, email=email)
            Account.objects.create(user=user)
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse("polls:index"))
        except IntegrityError:
            messages.error(request, 'This username is already taken.')
            return redirect(TO_LOGIN)
        except ValueError:
            messages.error(request, 'You must fill all the fields.')
            return redirect(TO_LOGIN)
    return render(request, "polls/login.html")


def logout_view(request):
    logout(request)
    return redirect(TO_LOGIN)


def index(request):
    if not request.user.is_authenticated:
        return redirect(TO_LOGIN)
    term = request.GET.get('search', '')
    if term:
        """
        A03:2021-Injection
        Comment out the below row and uncomment the next one for a fix
        """
        questions = Question.objects.raw("SELECT * FROM polls_question WHERE question_text LIKE '%%%s%%'" % term)
        #questions = Question.objects.filter(question_text__contains=term)
        if not questions:
            messages.error(request, 'No polls matched your search.')
    else:
        questions = Question.objects.none()
    latest_questions = Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[:20]
    context = { "questions": questions, 'latest_questions': latest_questions }
    return render(request, "polls/index.html", context)


class DetailView(LoginRequiredMixin, generic.DetailView):
    login_url = 'polls:login'
    model = Question
    template_name = "polls/detail.html"

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())


"""
A01:2021-Broken Access Control
Comment out the below row and uncomment the next two rows for a fix
"""
class ResultsView(generic.DetailView):
#class ResultsView(LoginRequiredMixin, generic.DetailView):
    #login_url = 'polls:login'
    model = Question
    template_name = "polls/results.html"


"""
Cross Site Request Forgery (CSRF)
Comment out the below row (the decorator) for a fix
"""
@csrf_exempt
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        return render(
            request, "polls/detail.html", {
                "question": question,
                "error_message": "You did not select a choice.",
        },)
    else:
        try:
            Vote.objects.create(user=request.user, choice=selected_choice)
        except IntegrityError as e:
            """
            A05:2021-Security Misconfiguration
            Comment out the two below rows and uncomment the third one for a fix
            """
            messages.error(request, "Error: " + str(e))
            messages.error(request, str(traceback.format_exc()))
            #messages.error(request, "You have already voted for this choice.")
            return redirect("polls:detail", pk=question_id)
        else:
            selected_choice.votes += 1
            selected_choice.save()
            return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))


def profile(request):
    if not request.user.is_authenticated:
        return redirect(TO_LOGIN)
    """
    A02:2021-Cryptographic Failures
    Comment out the below row and uncomment the next one for a fix
    """
    user = request.user
    #user = request.user.get_username()
    user_votes = Vote.objects.filter(user=request.user).select_related('choice__question').order_by("-vote_time")
    return render(request, 'polls/profile.html', { 'user': user, 'user_votes': user_votes })

django-polls/polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en-uk">

  <head>
    <title>Vote on Poll</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
  </head>

  <body>

    <a href="{% url 'polls:index' %}">Back to all polls</a>

    <form action="{% url 'polls:vote' question.id %}" method="POST">
      {% csrf_token %}
      <fieldset>
        <legend><h2>{{ question.question_text }}</h2></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
          <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
          <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
      </fieldset>
      <input type="submit" value="Vote">
    </form>

    {% if messages %}
    <ul class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
    </ul>
    {% endif %}

    <p></p>
    <a href="{% url 'polls:profile' %}">My profile</a>
    <p></p>
    <a href="{% url 'polls:logout' %}">Log out</a>

  </body>

</html>

django-polls/polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en-uk">

  <head>
    <title>Polls</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
  </head>

  <body>

    <h3>Search for a poll</h3>

    <form action="{% url 'polls:index' %}" method="GET">
      <input type="text" name="search" placeholder="Search">
      <input type="submit" value="Search">
    </form>
    <ul>
      {% for question in questions %}
      <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
      {% endfor %}
    </ul>

    {% if messages %}
    <ul class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
    </ul>
    {% endif %}

    <h3>Latest questions</h3>

    {% if latest_questions %}
      <ul>
      {% for question in latest_questions %}
      <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
      {% endfor %}
      </ul>
    {% else %}
      <p>No polls are available.</p>
    {% endif %}

    <p></p>
    <a href="{% url 'polls:profile' %}">My profile</a>
    <p></p>
    <a href="{% url 'polls:logout' %}">Log out</a>

  </body>

</html>

django-polls/polls/templates/polls/login.html
<!DOCTYPE html>
<html lang="en-uk">

  <head>
    <title>Login</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
  </head>

  <body>

    {% if messages %}
    <ul class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
    </ul>
    {% endif %}

    <h3>Log in</h3>
    <form action="{% url 'polls:login' %}" method="POST">
      {% csrf_token %}
      <input type="text" name="username" placeholder="Username">
      <input type="password" name="password" placeholder="Password">
      <input type="submit" value="Log in">
    </form>

    <h3>Register</h3>
    <form action="{% url 'polls:register' %}" method="POST">
      {% csrf_token %}
      <input type="text" name="username" placeholder="Username">
      <input type="email" name="email" placeholder="Email">
      <input type="password" name="password" placeholder="Password">
      <input type="submit" value="Register">
    </form>

  </body>

</html>

django-polls/polls/templates/polls/profile.html
<!DOCTYPE html>
<html lang="en-uk">

  <head>
    <title>My Profile</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
  </head>

  <body>

    <a href="{% url 'polls:index' %}">Back to all polls</a>

    <h3>All votes given by {{ user }}</h3>

    <ul>
    {% for vote in user_votes %}
      <li>You voted for "{{ vote.choice.choice_text }}" in poll "{{ vote.choice.question.question_text }}"
          at {{ vote.vote_time|date:"j/n/Y, G:i"}}.</li>
    {% endfor %}
    </ul>

    <p></p>
    <a href="{% url 'polls:logout' %}">Log out</a>

  </body>

</html>

django-polls/polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en-uk">
    
  <head>
    <title>Results</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
  </head>

  <body>

    <a href="{% url 'polls:index' %}">Back to all polls</a>

    <h1>{{ question.question_text }}</h1>
    
    <ul>
    {% for choice in question.choice_set.all %}
      <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>

    <p></p>
    <a href="{% url 'polls:profile' %}">My profile</a>
    <p></p>
    <a href="{% url 'polls:logout' %}">Log out</a>
    
  </body>

</html>

polls/templates/polls/votes.html
<!DOCTYPE html>
<html>

  <head>
    <title>Given Votes</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
  </head>

  <body>

    <a href="{% url 'polls:index' %}">Back to all polls</a>

    <h3>All given votes</h3>

    <ul>
    {% for vote in user_votes %}
      <li>You voted for "{{ vote.choice.choice_text }}" in poll "{{ vote.choice.question.question_text }}"
          at {{ vote.vote_time|date:"j/n/Y, G:i"}}.</li>
    {% endfor %}
    </ul>

    <a href="{% url 'polls:logout' %}">Log out</a>

  </body>

</html>